### PR TITLE
Remove assumptions about unhandled errors

### PR DESCRIPTION
**Pull request by sayhiben**
*Issue #, if available:*
#395

*Description of changes:*
The main function in index.js has a broad try/catch that handles all unhandled errors thrown when the action runs. However, it makes an intermittently incorrect assumption that the error thrown has a `.message` property. When this is not true, the stack trace is not emitted, preventing the end user from discovering the reason for the exception.

This commit changes the error handling to pass the entire error object to @ actions/toolkit/core, which then calls `.toString()` on the argument, effectively maintaining behavior for actual Error objects.

This commit does not correct the underlying causes of such errors; it only surfaces them

---

* [SURETHING] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws-actions/configure-aws-credentials/blob/master/CONTRIBUTING.md)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by sayhiben** [comment]
On a second glance at the issue, perhaps this wouldn't be sufficient; it seems the error object is actually `undefined`, which would still fail when actions/toolkit/core calls `toString` on it. I'll update this PR to explicitly handle undefined errors

**Comment by ajschmidt8** [comment]
@sayhiben, just checking in. Any idea when we can expect the update you mentioned?

My team could also benefit from this fix you are working on.

Appreciate your work!

**Comment by kellertk** [comment]
This is a good idea, but we will be migrating this action to Typescript in the near future, which will take care of ensuring correctness on the error type for us.

**Comment by sayhiben** [comment]
> @sayhiben, just checking in. Any idea when we can expect the update you mentioned?
> 
> My team could also benefit from this fix you are working on.
> 
> Appreciate your work!

I've been thinking about this one, but am not sure I'll get back to it, especially with @kellertk's good news re: strict typing. Looking forward to the next version. 

If you still want to investigate this version, create a fork and start by replacing wherever `error.message` is used with some stack tracing to see where the exception is being raised from - I'm no JS expert, but maybe `console.trace()` would do the trick. Then, at least it should give us some better idea of where our problems are originating

**Pull request closed without merging**
