### PR TITLE
chore: Fix typo in README

### PR DESCRIPTION
**Pull request by PureKrome**
> By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

Yeppers!

### CODE REVIEW

**Comment by allisaurus** [comment]
Hi @PureKrome ! Thanks for submitting this! 
As much as we appreciate creative emoji use, we need commit message to be [semantic](https://github.com/zeke/semantic-pull-requests) so they play nice with our automation. Would you mind changing it to something boring like "chore: Fix typo in README" ?

**Comment by PureKrome** [comment]
Done @allisaurus !

**Comment by allisaurus** [comment]
@PureKrome unfortunately we need the actual _commit_ message to be semantic, not just the PR title. The easiest way to do this is probably running [`git commit --amend` ](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History), editing the msg, and then force pushing to your branch. When the commit history changes it should re-run the automated checks. Thanks again!

**Comment by PureKrome** [comment]
👀 @allisaurus 

fixed 💪🏻

**Review by allisaurus — APPROVED** [review]

**Pull request merged**
