### PR TITLE
Add role-chaining support

### PR DESCRIPTION
**Pull request by siggimoo**
*Description of changes:*

Adds boolean input option `role-chaining` which, when true, uses existing credentials in the environment to assume a role.

---

* [✅] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws-actions/configure-aws-credentials/blob/master/CONTRIBUTING.md)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by siggimoo** [comment]
Hi, can I get another approval here? There was a change to master before I could merge things. Thanks!

**Comment by jamengual** [comment]
Any way to accelerate this?

**Comment by siggimoo** [comment]
Looks like there was a mass-closure of PRs related to the release of 2.0. I don't think it was intentional as the behavior does not appear to be in the new version. I'll resubmit my changes in a new PR. I too want this.

**Comment by siggimoo** [comment]
Opened new PR [#688](https://github.com/aws-actions/configure-aws-credentials/pull/688).

**Comment by kellertk** [comment]
> Looks like there was a mass-closure of PRs related to the release of 2.0. I don't think they were intentionally denying this as the behavior does not appear to be in the new version. 

Correct! Thanks for opening a new PR, we'll take a look at that one.

**Pull request closed without merging**
