### PR TITLE
Updated node version for action.yml

### PR DESCRIPTION
**Pull request by lynxSven**
Description

Updated the node version from 12 to 16, due to the deprecation of the github node12 actions.
For more Infos read the blog post provided by Github:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

---

*[x ] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws-actions/configure-aws-credentials/blob/master/CONTRIBUTING.md)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by asclearuc — APPROVED** [review]

**Comment by inductor** [comment]
`aws-actions/configure-aws-credentials@v1-node16` is already in the doc.

**Comment by webkod3r** [comment]
> `aws-actions/configure-aws-credentials@v1-node16` is already in the doc.

I see the branch. Is there a plan to roll out this release? I've seen it's lots of commits behind master.

**Review by remithomas — APPROVED** [review]

**Comment by zyv** [comment]
This is related to #632.

**Comment by JasonIamAUnixAdmin** [comment]
Is this project maintained or do we need to find another project or fork?

**Comment by zyv** [comment]
> Is this project maintained or do we need to find another project or fork?

I think the main contributor in the last half a year was a guy that goes by the name of @dependabot...

**Comment by lynxSven** [comment]
@clareliguori or @kellertk maybe someone of you can review this changes or dismiss these changes because there are other planes for this change (like the configure-aws-credentials@v1-node16 branch)?
Thank you.

**Comment by kellertk** [comment]
This has been discussed in many issues before. We will not merge this as is.

> Is this project maintained or do we need to find another project or fork?

@JasonIamAUnixAdmin We absolutely are working on this, but haven't had dedicated capacity to push changes recently. This is no longer the case. Unless something changes, expect a major update from us within the next few months.

**Comment by lynxSven** [comment]
Thank you for the clarification @kellertk

**Pull request closed without merging**
