### PR TITLE
Add role-chaining support

### PR DESCRIPTION
**Pull request by siggimoo**
Description of changes:

Adds boolean input option `role-chaining` which, when true, uses existing credentials in the environment to assume a role.

---

* [✅] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws-actions/configure-aws-credentials/blob/main/CONTRIBUTING.md)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by zeljkotjja — DISMISSED** [review]
LGTM!

**Comment by siggimoo** [comment]
Still waiting on maintainer approval ...

**Comment by AnitaErnszt** [comment]
@kellertk

**Comment by peterwoodworth** [comment]
Thanks for submitting this PR, and sorry for the delay here. I feel pretty uncomfortable about the lack of testing (which we're actively working on implementing for the next major release), but on the face of it this looks good to me and I don't think it risks breaking existing users.

I'll do some manual testing before the end of the week, and take action on this PR following those tests.

**Review by peterwoodworth — APPROVED** [review]
Looks good to me, thanks!

**Comment by nunosousa-dev** [comment]
This PR is not tagged or released yet right?
We got this to work only using main as ref :)

**Comment by kevcube** [comment]
@peterwoodworth can we get a release with this?

**Comment by peterwoodworth** [comment]
@kevcube @nunosousa-dev `v2` should feature this now, and `v2.1.0` has been released

**Pull request merged**
