### PR TITLE
chore: Add token permissions to check.yml workflow

### PR DESCRIPTION
**Pull request by varunsh-coder**
*Description of changes:*

This PR adds token `permissions` to the check.yml workflow. This is a security best practice as per [GitHub](https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/) and is checked by [OSSF Scorecard](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions). 

1. I am collating security information about different GitHub Actions in an [open-source knowledge-base](https://github.com/step-security/secure-workflows/tree/main/knowledge-base) to calculate minimum `GITHUB_TOKEN` permissions and restrict outbound traffic to allowed domains. As an owner of `aws-actions/configure-aws-credentials` Action, please review info about it in the knowledge-base [here](https://github.com/step-security/secure-workflows/blob/main/knowledge-base/aws-actions/configure-aws-credentials/action-security.yml) - specifically the reason for the token permissions the Action needs and expected outbound calls it makes. 
2. JFYI - You can easily add token permissions and other security best practices to other workflows in this repo using https://app.stepsecurity.io. It uses the knowledge base mentioned above...Do let me know if you have feedback. Thanks!

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by peterwoodworth** [comment]
@mergifyio update

**Review by peterwoodworth — COMMENTED** [review]
@varunsh-coder we have more than one action that doesn't specify permissions (some of which have been added since this PR was created), why call out and add them to just `check.yml`? Also, what exactly is [this file](https://github.com/step-security/secure-workflows/blob/main/knowledge-base/actions/aws-actions/configure-aws-credentials/action-security.yml) supposed to indicate/mean?

**Comment by varunsh-coder** [comment]
Hi @peterwoodworth, [this file](https://github.com/step-security/secure-workflows/blob/main/knowledge-base/actions/aws-actions/configure-aws-credentials/action-security.yml) is part of the https://github.com/step-security/secure-workflows project and has information about token permissions needed by the `aws-actions/configure-aws-credentials` GitHub Action. When one tries to add token permissions to a workflow that uses this Action, that file is used to calculate the permissions needed. 

The project has such metadata for other Actions as well. As an example, if you try to add permissions to the CodeQL workflow in this repo with the below link, similar file for the [CodeQL](https://github.com/step-security/secure-workflows/blob/main/knowledge-base/actions/github/codeql-action/analyze/action-security.yml) Action and others actions in the workflow are used to calculate permissions. 
https://app.stepsecurity.io/secureworkflow/aws-actions/configure-aws-credentials/codeql-analysis.yml/master?enable=permissions

w.r.t why I added token permissions only to `check.yml` I am not sure. If you want, I can push a commit to this PR and add permissions to the remaining workflow files as well. Please let me know. Thanks!

**Review by peterwoodworth — CHANGES_REQUESTED** [review]
> If you want, I can push a commit to this PR and add permissions to the remaining workflow files as well. Please let me know. Thanks!

That would be excellent @varunsh-coder, thank you so much!

**Comment by peterwoodworth** [comment]
Closing due to staleness. Please reopen an issue if you would like this to remain on our radar, or submit a new PR with the requested changes. Thanks!

**Pull request closed without merging**
