### PR TITLE
chore: update role duration description

### PR DESCRIPTION
**Pull request by dacbd**
https://github.com/aws-actions/configure-aws-credentials/blob/67fbcbb121271f7775d2e7715933280b06314838/index.js#L10
https://github.com/aws-actions/configure-aws-credentials/blob/67fbcbb121271f7775d2e7715933280b06314838/index.js#L315

*Description of changes:*

update the actions.yml default description to refect the proper value when using oidc

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by casperdcl** [comment]
indeed; the 1h mentioned in https://github.com/aws-actions/configure-aws-credentials#assuming-a-role is currently quite hidden.

**Review by peterwoodworth — CHANGES_REQUESTED** [review]
Good callout @dacbd, thanks for the submission.

Could we also put this in the README somewhere? Currently the only mention of default length (that I found on a short look) is just under the `Assuming a Role` section. Maybe we could mention here, and/or in the OIDC section that there's another default duration.

**Comment by dacbd** [comment]
@peterwoodworth thanks for the attention. I'll give this greater attention and Include a README addition before the end of the week.

**Review by peterwoodworth — CHANGES_REQUESTED** [review]
Thanks @dacbd, when you get around to this could you also address the changes seen [here](https://github.com/aws-actions/configure-aws-credentials/pull/513) in this PR? When this PR is merged, the role duration will default to 1 hour if a session token is provided. I'd like you to update the readme and action.yml description to account for this change, and then we can merge this PR after that one is merged.

**Comment by dacbd** [comment]
@peterwoodworth I've included some spacing that imo helps communicate these defaults when users are quickly skimming through the readme docs. If it's too opinionated of a change we can revert [`a6ddb3c`
](https://github.com/aws-actions/configure-aws-credentials/pull/486/commits/a6ddb3cab93799e4896c27250b75e67570a8929d)
see example:
image

**Comment by peterwoodworth** [comment]
Looks great to me @dacbd, will approve it as soon as the other PR is merged 🙂

**Review by peterwoodworth — APPROVED** [review]
Thanks @dacbd!

**Comment by peterwoodworth** [comment]
@mergifyio update

**Pull request merged**
